name: 'Create Release Tag'
description: 'Creates a release tag based on the specified type (dev, rc, or prod)'
author: 'GitHub Actions'

inputs:
  release_type:
    description: 'Type of release to create. One of "dev", "rc", or "prod". If not provided, the type will be inferred from the git ref.'
    required: false
    default: 'dev'

outputs:
  tag_name:
    description: 'The name of the created tag'
    value: ${{ steps.create_tag.outputs.tag_name }}
  release_type:
    description: 'The type of release that was created'
    value: ${{ steps.determine_type.outputs.type }}

runs:
  using: 'composite'
  steps:
    - name: Determine release type
      id: determine_type
      shell: bash
      run: |
        RELEASE_TYPE="${{ inputs.release_type }}"
        
        # If release_type is empty or not provided, infer from branch
        if [ -z "$RELEASE_TYPE" ]; then
          BRANCH_NAME="${GITHUB_REF_NAME}"
          echo "Release type not provided, inferring from branch: $BRANCH_NAME"
          
          if [ "$BRANCH_NAME" == "main" ]; then
            RELEASE_TYPE="dev"
            echo "Inferred release type: dev (from main branch)"
          elif [ "$BRANCH_NAME" == "stable" ]; then
            RELEASE_TYPE="rc"
            echo "Inferred release type: rc (from stable branch)"
          elif [ "$BRANCH_NAME" == "dev1" ]; then
            RELEASE_TYPE="dev"
            echo "Inferred release type: dev (from dev1 branch)"
          else
            RELEASE_TYPE="dev"
            echo "Inferred release type: dev (default)"
          fi
        else
          echo "Using provided release type: $RELEASE_TYPE"
        fi
        
        echo "type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
    
    - name: Fetch tags
      shell: bash
      run: git fetch --tags
    
    - name: Create tag
      id: create_tag
      shell: bash
      run: |
        RELEASE_TYPE="${{ steps.determine_type.outputs.type }}"
        
        # Get the latest v0.x.0 final release tag (not rc or dev)
        LATEST_RELEASE=$(git tag -l "v0.*.0" | grep -v "rc" | grep -v "dev" | sort -V | tail -n1)
        
        if [ -z "$LATEST_RELEASE" ]; then
          VERSION_NUMBER=1
          echo "No existing release found, starting with version 1"
        else
          MIDDLE=$(echo $LATEST_RELEASE | sed -n 's/v0\.\([0-9]*\)\.0/\1/p')
          echo "Current release version: $MIDDLE"
          VERSION_NUMBER=$MIDDLE
        fi
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        case "$RELEASE_TYPE" in
          dev)
            # Bump version for dev tags too
            VERSION_NUMBER=$((VERSION_NUMBER + 1))
            
            # Create timestamp in format YYYYMMDDHH
            TIMESTAMP=$(date -u +'%Y%m%d%H')
            TAG_NAME="v0.${VERSION_NUMBER}.0-dev${TIMESTAMP}"
            
            # Check if tag already exists
            if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "⚠️  Tag $TAG_NAME already exists, skipping creation"
              echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            echo "Creating dev tag: $TAG_NAME"
            DESCRIBE=$(git describe --always --tags || echo "initial")
            git tag -a $TAG_NAME -m "Development release $TAG_NAME (from $DESCRIBE)"
            git push origin $TAG_NAME
            ;;
          
          rc)
            # Use git describe to find the nearest tag
            NEAREST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            
            if [ -z "$NEAREST_TAG" ]; then
              VERSION_NUMBER=1
              echo "No existing tags found, starting with version 1"
            else
              echo "Nearest tag in history: $NEAREST_TAG"
              
              # Extract version number from nearest tag (could be dev, rc, or prod)
              # Remove 'v' prefix and extract middle number
              MIDDLE=$(echo $NEAREST_TAG | sed -n 's/v0\.\([0-9]*\)\.0.*/\1/p')
              
              if [ -z "$MIDDLE" ]; then
                VERSION_NUMBER=1
                echo "Could not parse version from $NEAREST_TAG, using version 1"
              else
                VERSION_NUMBER=$MIDDLE
                echo "Extracted version: $VERSION_NUMBER from nearest tag"
              fi
            fi
            
            VERSION_NUMBER=$((VERSION_NUMBER + 1))
            TAG_NAME="v0.${VERSION_NUMBER}.0-rc1"
            
            # Check if tag already exists
            if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
              echo "⚠️  Tag $TAG_NAME already exists, skipping creation"
              echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            echo "Creating RC tag: $TAG_NAME (bumped from nearest tag)"
            DESCRIBE=$(git describe --always --tags || echo "initial")
            git tag -a $TAG_NAME -m "Release candidate $TAG_NAME (from $DESCRIBE)"
            git push origin $TAG_NAME
            ;;
          
          prod)
            # Use git describe to find the nearest tag
            NEAREST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            
            if [ -z "$NEAREST_TAG" ]; then
              VERSION_NUMBER=1
              echo "No existing tags found, starting with version 1"
            else
              echo "Nearest tag in history: $NEAREST_TAG"
              
              # Extract version number from nearest tag (could be dev, rc, or prod)
              MIDDLE=$(echo $NEAREST_TAG | sed -n 's/v0\.\([0-9]*\)\.0.*/\1/p')
              
              if [ -z "$MIDDLE" ]; then
                VERSION_NUMBER=1
                echo "Could not parse version from $NEAREST_TAG, using version 1"
              else
                VERSION_NUMBER=$MIDDLE
                echo "Extracted version: $VERSION_NUMBER from nearest tag"
              fi
            fi
            
            VERSION_NUMBER=$((VERSION_NUMBER + 1))
            RC_TAG="v0.${VERSION_NUMBER}.0-rc1"
            FINAL_TAG="v0.${VERSION_NUMBER}.0"
            
            # Check if RC tag already exists
            if git rev-parse "$RC_TAG" >/dev/null 2>&1; then
              echo "⚠️  RC tag $RC_TAG already exists"
            else
              echo "Creating RC tag: $RC_TAG"
              DESCRIBE=$(git describe --always --tags || echo "initial")
              git tag -a $RC_TAG -m "Release candidate $RC_TAG (from $DESCRIBE)"
              git push origin $RC_TAG
            fi
            
            # Check if final tag already exists
            if git rev-parse "$FINAL_TAG" >/dev/null 2>&1; then
              echo "⚠️  Production tag $FINAL_TAG already exists, skipping"
              TAG_NAME=$FINAL_TAG
              echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            echo "Creating production tag: $FINAL_TAG"
            DESCRIBE=$(git describe --always --tags || echo "initial")
            git tag -a $FINAL_TAG -m "Production release $FINAL_TAG (from $DESCRIBE)"
            git push origin $FINAL_TAG
            
            TAG_NAME=$FINAL_TAG
            ;;
          
          *)
            echo "❌ Error: Invalid release type '$RELEASE_TYPE'"
            echo "Valid options: dev, rc, prod"
            exit 1
            ;;
        esac
        
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "✅ Successfully created tag: $TAG_NAME"

branding:
  icon: 'tag'
  color: 'blue'
